apiVersion: v1
kind: Pod
metadata:
  name: arxivflow-pvc-inspector
spec:
  containers:
    - name: arxivflow-pvc-inspector-container
      image: busybox
      command: ["sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: arxivflow-pvc
          mountPath: /data
  volumes:
    - name: arxivflow-pvc
      persistentVolumeClaim:
        claimName: arxivflow-pvc
