apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arxivflow-pvc
spec:
  accessModes:
    - ReadWriteOnce # Use ReadWriteMany if multiple Pods need to write to the volume.
  resources:
    requests:
      storage: 5Gi # We can increase but NOT decrease the storage size later.
