# Jobs are batch processing resources meant to run once or on a schedule.
apiVersion: batch/v1
kind: Job
metadata:
  name: allenai-specter-2-proximity-embeddings
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0 # Run Docker image as user root.
      containers:
        - name: arxivflow-embeddings
          image: dashaikh10/arxivflow-papervec:latest
          command: ["python", "-m", "src.lib.allenai.main"]
          envFrom:
            - secretRef:
                name: papervec-env
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: arxivflow-pvc
              mountPath: /app/data # Mount the persistent volume claim to the container in the path /app/data.
              subPath: arxivflow/db
            - name: arxivflow-pvc
              mountPath: /app/src/logs
              subPath: arxivflow/papervec/logs
            - name: ssh-key
              mountPath: /root/.ssh # Mount the secret with the SSH key to the container.
      nodeSelector:
        gpu: l4 # Ada Lovelace 24GB GDDR6 GPU node.
      restartPolicy: Never

      volumes:
        - name: arxivflow-pvc
          persistentVolumeClaim:
            claimName: arxivflow-pvc
        - name: ssh-key
          secret:
            secretName: ssh-key-secret
  backoffLimit: 2
